defaults:
    - _self_
    - general : general_default
    - model : model_default
    - train : train_default
    - dataset : fp2mol
    
base_data_path: /data/nas-gpu/wang/mzare008/codes/DiffMS/

hydra:
  job:
    chdir: True
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${general.name}